version: '2'
services:
  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog
    command: postgres -c fsync=off

  admin:
    image: sergkoba/blog:latest-admin
    command:  rackup --port 3000 --host 0.0.0.0
    links:
      - db
    environment:
      RACK_ENV: production

  front:
    image: sergkoba/blog:latest
    command:  rackup --port 3001 --host 0.0.0.0
    links:
      - db
    volumes:
      - /app/public/sitemaps
    environment:
      RACK_ENV: production