apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "chart.name" . }}-api-secret"
  labels:
    app.kubernetes.io/name: "{{ include "chart.name" . }}-api-secret"
    helm.sh/chart: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  API_TOKEN: "RnJPTU9SMlhKTlNCMVloeDFNRDRDNGt0NGRTek1lRDQ="