apiVersion: v1
kind: Service
metadata:
  name: "{{ include "chart.fullname" . }}-front-service"
  labels:
    app.kubernetes.io/name: "{{ include "chart.name" . }}-front-service"
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: "{{ include "chart.name" . }}-front"
    app.kubernetes.io/instance: {{ .Release.Name }}
