apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "{{ include "chart.fullname" . }}-front-deployment"
  labels:
    app.kubernetes.io/name: "{{ include "chart.name" . }}-front"
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "chart.name" . }}-front"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "chart.name" . }}-front"
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-front"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["rackup", "--port", "3001", "--host", "0.0.0.0"]
          env:
            - name: RACK_ENV
              value: "production"
            - name: POSTGRES_HOST
              value: "{{ .Chart.Name }}-postgres-service"
          envFrom:
            - secretRef:
                name: "{{ include "chart.name" . }}-postgres-secret"
            - secretRef:
                name: "{{ include "chart.name" . }}-api-secret"
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      imagePullSecrets:
        - name: regcred
