kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{ include "chart.name" . }}-postgres-pv-volume"
  labels:
    type: local
    app.kubernetes.io/name: "{{ include "chart.name" . }}-postgres-pv-volume"
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "chart.name" . }}-postgres-pv-claim"
  labels:
    app.kubernetes.io/name: "{{ include "chart.name" . }}-postgres-pv-claim"
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi