# frozen_string_literal: true
source 'https://rubygems.org'

ruby '2.3.1'

# Db
gem 'sequel'
gem 'pg'

# Routes and controllers
gem 'hanami-router'
gem 'hanami-controller'

# Trailblazer
gem 'dry-validation'
gem 'trailblazer'
gem 'trailblazer-loader'
gem 'trailblazer-cells'
gem 'cells-erb'
gem 'formular'

# Web server
gem 'puma'

group :development do
  # Rerun web server when code changes (see docker-compose.dev.yml)
  gem 'rerun'

  # Debugger
  gem 'pry'
  gem 'better_errors'
  gem 'binding_of_caller'

  # Console
  gem 'rack-console'
end