# frozen_string_literal: true
source 'https://rubygems.org'

ruby '2.3.1'

# Db
gem 'sequel'
gem 'pg'

# Routes and controllers
gem 'hanami-router'
gem 'hanami-controller'

# Trailblazer
gem 'dry-validation'
gem 'trailblazer'
gem 'trailblazer-loader'
gem 'trailblazer-cells'
gem 'cells-erb'

# Web server
gem 'puma'

# Debugger
gem 'pry'