require 'ostruct'
require 'hanami/controller'
require 'hanami/action/session'
require 'hanami/helpers'
require 'sitemap_generator'
require './init/router'

require_dir 'lib'
fake_load 'init/r18n.rb'
fake_load 'init/better_errors.rb'
fake_load 'init/session.rb'
fake_load 'init/db.rb'
fake_load 'init/trailblazer.rb'
fake_load 'init/static.rb'
fake_load 'init/sass.rb'
require_dir 'app/models'
require_dir 'app/controllers'