#!/usr/bin/env ruby
require 'thor'
require 'logger'
require './loaders'
require 'sitemap_generator'

def use(*)
end
fake_load 'app.rb'

class MyCLI < Thor
  desc 'routes', 'List all app routes'
  def routes
    Router.print_routes
  end

  desc 'sitemap_generate', 'Generate public/sitemap.xml.gz file'
  def sitemap_generate
    SitemapGenerator::Interpreter.run(config_file: 'config/sitemap.rb', verbose: true)
  end
end

MyCLI.start(ARGV)