#!/usr/bin/env ruby
require 'thor'
require 'logger'
require './loaders'

def use(*)
end
fake_load 'app.rb'

class MyCLI < Thor
  desc 'routes', 'List all app routes'
  def routes
    Router.print_routes
  end

  desc 'sitemap_generate', 'Generate public/sitemap.xml.gz file'
  def sitemap_generate
    Sitemap::Generate.()
  end
end

MyCLI.start(ARGV)